#!/bin/sh

uci -q get system.@open_init[0] > "/dev/null" || uci -q add system open_init > "/dev/null"

if ! uci -q get system.@open_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"

		delete system.ntp.server
		add_list system.ntp.server="ntp.tencent.com"
		add_list system.ntp.server="ntp1.aliyun.com"
		add_list system.ntp.server="ntp.ntsc.ac.cn"
		add_list system.ntp.server="cn.ntp.org.cn"

		set system.@open_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@open_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.vsean.net/openwrt"
	uci -q set system.@open_init[0].opkg_mirror="$opkg_mirror"
	uci -q commit system
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"

sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci commit firewall

#uci delete network.globals.ula_prefix
#uci delete network.globals.packet_steering
uci commit network

/etc/init.d/ddns disable

#hwclock -l -r
#hwclock -l -w

#echo "echo "x86" > /tmp/sysinfo/model" >> /etc/crontabs/root
#crontab /etc/crontabs/root

exit 0
