#!/bin/sh

uci -q get system.@open_init[0] > "/dev/null" || uci -q add system open_init > "/dev/null"

if ! uci -q get system.@open_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@open_init[0].lang="1"
		commit system
	EOF
fi

uci set system.ntp.enable_server='1'
uci set system.ntp.interface='lan'
uci set system.ntp.use_dhcp='0'
uci commit system

uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

uci set dhcp.dnsmasq.cachesize='0'
uci set dhcp.dnsmasq.min_cache_ttl='0'
uci set dhcp.dnsmasq.max_cache_ttl='0'
uci set dhcp

sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

ln -sf "/sbin/ip" "/usr/bin/ip"

rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
