#!/bin/sh

# Language
uci set luci.main.lang=auto
uci commit luci

# Automount
uci set fstab.@global[0].anon_mount=1
uci commit fstab

# Timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.ntp.enable_server='1'
uci set system.ntp.interface='lan'
uci set system.ntp.use_dhcp='0'
delete system.ntp.server
uci add_list system.ntp.server='ntp1.aliyun.com'
uci commit system

# Dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# dnsmasq
uci set dhcp.cfg01411c.cachesize='0'
uci set dhcp.cfg01411c.min_cache_ttl='0'
uci set dhcp.cfg01411c.max_cache_ttl='0'
uci set dhcp
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#SSH Key
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

#rm -rf /tmp/luci-modulecache
#rm -f /tmp/luci-indexcache

exit 0
