#!/bin/sh

#Language
uci set luci.main.lang="auto"
uci commit luci

#Automount
uci set fstab.@global[0].anon_mount="1"
uci commit fstab

#Timezone
uci set system.@system[0].timezone="CST-8"
uci set system.@system[0].zonename="Asia/Shanghai"

uci del system.ntp.server
uci set system.ntp.use_dhcp="0"
uci set system.ntp.enabled="1"
uci add_list system.ntp.server="ntp1.aliyun.com"
uci add_list system.ntp.server="ntp.tencent.com"
uci add_list system.ntp.server="ntp.ntsc.ac.cn"
uci commit system

#Dropbear
uci set dropbear.@dropbear[0].Interface="lan"
uci commit dropbear

# dnsmasq
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.@dnsmasq[0].cachesize="0"
uci set dhcp.@dnsmasq[0].min_cache_ttl="0"
uci set dhcp.@dnsmasq[0].max_cache_ttl="0"
uci set dhcp.@dnsmasq[0].dnsforwardmax='1500'
uci commit dhcp

#Firewall
#uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].synflood_protect='0'
uci commit firewall

#Enable Packet Steering
uci del network.@globals[0].ula_prefix
uci set network.@globals[0].packet_steering='0'
#uci set network.@globals[0].packet_steering='2'
#uci set network.@globals[0].steering_flows='128'
uci del_list network.@device[0].ports='eth0'
uci add_list network.@device[0].ports='eth1'
uci add_list network.@device[0].ports='eth2'
uci add_list network.@device[0].ports='eth3'
#uci del network.wan
uci set network.wan.device='eth0'
uci set network.wan.proto='pppoe'
uci del network.wan6
uci set network.lan.ip6assign='64'
uci set network.lan.ip6ifaceid='eui64'
uci commit network
/etc/init.d/odhcpd restart

/etc/init.d/packet_steering disable
/etc/init.d/packet_steering stop
/etc/init.d/irqbalance disable
/etc/init.d/irqbalance stop

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

[ ! -f "/usr/bin/ip" ] && [ -f "/sbin/ip" ] && ln -sf "/sbin/ip" "/usr/bin/ip"

#SSH Key
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
