#!/bin/sh /etc/rc.common

START=99

start() {

    sysctl -w net.netfilter.nf_conntrack_max=65536

    enable_offload() {
        ethtool -K "$1" "$2" on 2>/dev/null || :
    }

    for NIC_PATH in /sys/class/net/*; do
        NIC=$(basename "$NIC_PATH")

        [ -d "$NIC_PATH/device" ] || continue
        IF_TYPE=$(cat "$NIC_PATH/type" 2>/dev/null)
        [ "$IF_TYPE" != "1" ] && continue

            enable_offload "$NIC" rx-checksum
            enable_offload "$NIC" tx-checksum-ip-generic || {
                enable_offload "$NIC" tx-checksum-ipv4
                enable_offload "$NIC" tx-checksum-ipv6
            }

            for f in tx-scatter-gather rx tx sg tso; do
                enable_offload "$NIC" "$f"
            done

            for i in eth0 eth1 eth2 eth3; do ethtool -K "$i" gro off rx-gro-list off gso off; done

            for protocol in tcp4 udp4 tcp6 udp6; do
                ethtool -N eth0 rx-flow-hash $protocol sdfn
            done

            DRIVER=$(ethtool -i "$NIC" 2>/dev/null | awk '/driver:/ {print $2}')
            if [ "$DRIVER" = "igc" ]; then
            ethtool -L "$NIC" combined "$threads" 2>/dev/null || :

                RX_MAX=$(ethtool -g "$NIC" 2>/dev/null | awk '/Pre-set maximums:/ {p=1;next} p && /^RX:/ {print $2;exit}')
                TX_MAX=$(ethtool -g "$NIC" 2>/dev/null | awk '/Pre-set maximums:/ {p=1;next} p && /^TX:/ {print $2;exit}')

                [ -n "$RX_MAX" ] && ethtool -G "$NIC" rx "$RX_MAX" 2>/dev/null
                [ -n "$TX_MAX" ] && ethtool -G "$NIC" tx "$TX_MAX" 2>/dev/null
            fi
    done
}
