#!/bin/sh /etc/rc.common

START=99

start() {
    rfc=2048
    cfr=8192
    threads=$(grep -c "processor" "/proc/cpuinfo")

    cpu_mask=$(printf '%x' $(( (1 << threads) - 1 )))

    #for fileRps in /sys/class/net/eth*/queues/rx-*/rps_cpus; do
    #    [ -e "$fileRps" ] && echo "$cpu_mask" > "$fileRps"
    #done

    #for fileRfc in /sys/class/net/eth*/queues/rx-*/rps_flow_cnt; do
    #    [ -e "$fileRfc" ] && echo "$rfc" > "$fileRfc"
    #done

    #for fileRps in /sys/class/net/eth*/queues/tx-*/xps_cpus; do
    #    [ -e "$fileRps" ] && echo "$cpu_mask" > "$fileRps"
    #done

    #sysctl -w net.core.rps_sock_flow_entries="$(( cfr * threads ))" >/dev/null

    #for base_irq in 137 142 147 152; do
    #    for i in 0 1 2 3; do
    #        irq=$((base_irq + i))
    #        mask=$((1 << i))
    #        echo "Setting IRQ $irq to affinity $mask"
    #        echo "$mask" > "/proc/irq/$irq/smp_affinity"
    #    done
    #done

    sysctl -w net.netfilter.nf_conntrack_max=65536 >/dev/null

    #echo 1 > /proc/sys/net/ipv4/conf/br-lan/proxy_arp

    echo 65535 > /proc/sys/net/core/somaxconn
    echo 16384 > /proc/sys/net/ipv4/tcp_max_syn_backlog
    echo 16384 > /proc/sys/net/core/netdev_max_backlog

    mem_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    if [ "$mem_kb" -ge 4194304 ]; then
        t_max=134217728; c_max=4194304
    elif [ "$mem_kb" -ge 1048576 ]; then
        t_max=67108864; c_max=4194304
    else
        t_max=33554432; c_max=2097152
    fi

    echo "$t_max" > /proc/sys/net/core/rmem_max
    echo "$t_max" > /proc/sys/net/core/wmem_max
    echo "4096 87380 $t_max" > /proc/sys/net/ipv4/tcp_rmem
    echo "4096 65536 $t_max" > /proc/sys/net/ipv4/tcp_wmem

    enable_offload() {
        ethtool -K "$1" "$2" on 2>/dev/null || :
    }

    for NIC_PATH in /sys/class/net/*; do
        NIC=$(basename "$NIC_PATH")

        [ -d "$NIC_PATH/device" ] || continue
        IF_TYPE=$(cat "$NIC_PATH/type" 2>/dev/null)
        [ "$IF_TYPE" != "1" ] && continue

            enable_offload "$NIC" rx-checksum
            enable_offload "$NIC" tx-checksum-ip-generic || {
                enable_offload "$NIC" tx-checksum-ipv4
                enable_offload "$NIC" tx-checksum-ipv6
            }

            for f in tx-scatter-gather rx tx sg gso gro tso; do
                enable_offload "$NIC" "$f"
            done

            ethtool -K "$NIC" rx-gro-list off

            DRIVER=$(ethtool -i "$NIC" 2>/dev/null | awk '/driver:/ {print $2}')
            if [ "$DRIVER" = "igc" ]; then
            ethtool -L "$NIC" combined "$threads" 2>/dev/null || :

                RX_MAX=$(ethtool -g "$NIC" 2>/dev/null | awk '/Pre-set maximums:/ {p=1;next} p && /^RX:/ {print $2;exit}')
                TX_MAX=$(ethtool -g "$NIC" 2>/dev/null | awk '/Pre-set maximums:/ {p=1;next} p && /^TX:/ {print $2;exit}')

                [ -n "$RX_MAX" ] && ethtool -G "$NIC" rx "$RX_MAX" 2>/dev/null
                [ -n "$TX_MAX" ] && ethtool -G "$NIC" tx "$TX_MAX" 2>/dev/null
            fi
    done
}
